name: at-clone
dependencies:
- astroid=1.4.4=py35_0
- attrs=15.2.0=py35_0
- decorator=4.0.10=py35_0
- ipython=5.1.0=py35_0
- ipython_genutils=0.1.0=py35_0
- lazy-object-proxy=1.2.1=py35_0
- logilab-common=1.0.2=py35_0
- openssl=1.0.2h=1
- path.py=8.2.1=py35_0
- pep8=1.7.0=py35_0
- pexpect=4.0.1=py35_0
- pickleshare=0.7.3=py35_0
- pip=8.1.2=py35_0
- prompt_toolkit=1.0.3=py35_0
- ptyprocess=0.5.1=py35_0
- pygments=2.1.3=py35_0
- pylint=1.5.4=py35_0
- python=3.5.2=0
- pytz=2016.6.1=py35_0
- readline=6.2=2
- setuptools=25.1.6=py35_0
- simplegeneric=0.8.1=py35_1
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- traitlets=4.2.2=py35_0
- wcwidth=0.1.7=py35_0
- wheel=0.29.0=py35_0
- wrapt=1.10.6=py35_0
- xz=5.2.2=0
- zlib=1.2.8=3
- pip:
  - bokeh==0.11.1
  - ipython-genutils==0.1.0
  - numpy==1.11.0
  - prompt-toolkit==1.0.3
  - tornado==4.3

